[2024-07-30 10:20:12 +0900] [942791] [INFO] Starting gunicorn 22.0.0
[2024-07-30 10:20:12 +0900] [942791] [INFO] Listening at: http://0.0.0.0:5000 (942791)
[2024-07-30 10:20:12 +0900] [942791] [INFO] Using worker: eventlet
[2024-07-30 10:20:12 +0900] [942794] [INFO] Booting worker with pid: 942794
[2024-07-30 10:20:12 +0900] [942794] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/geventlet.py", line 143, in init_process
    super().init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 's'
[2024-07-30 10:20:12 +0900] [942794] [INFO] Worker exiting (pid: 942794)
[2024-07-30 10:20:12 +0900] [942791] [ERROR] Worker (pid:942794) exited with code 3
[2024-07-30 10:20:12 +0900] [942791] [ERROR] Shutting down: Master
[2024-07-30 10:20:12 +0900] [942791] [ERROR] Reason: Worker failed to boot.
[2024-07-30 10:21:56 +0900] [942953] [INFO] Starting gunicorn 22.0.0
[2024-07-30 10:21:56 +0900] [942953] [INFO] Listening at: http://0.0.0.0:5000 (942953)
[2024-07-30 10:21:56 +0900] [942953] [INFO] Using worker: eventlet
[2024-07-30 10:21:56 +0900] [942956] [INFO] Booting worker with pid: 942956
[2024-07-30 10:21:56 +0900] [942956] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/geventlet.py", line 143, in init_process
    super().init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 's'
[2024-07-30 10:21:56 +0900] [942956] [INFO] Worker exiting (pid: 942956)
[2024-07-30 10:21:56 +0900] [942953] [ERROR] Worker (pid:942956) exited with code 3
[2024-07-30 10:21:56 +0900] [942953] [ERROR] Shutting down: Master
[2024-07-30 10:21:56 +0900] [942953] [ERROR] Reason: Worker failed to boot.
